export const colors = {
  white: "#FFFFFF",
  black: "#000",
  blue: "#2D317F",
  navy_blue: "#040921",
  light_grey: "#ebebed",
  dark_grey: "#EBEBED",
  v_dark_grey: "#4D4D4D",
  orange: "#F18222",
  yellow: "#FCB62E",
  violet: "#47184E",
  petroli: "#18374E",
  dark_red: "#AF3F3E",
  dark_violet: "#754F9B",
  green: "#ABB560",
  light_green: "#A0CE64",
  dark_green: "#669578",
  dark_petroli: "#5687A7",
  light_petroli: "#69B8BE",
  dark_brown: "#B87F5B",
  light_brown: "#D07E5A",
  ratty: "#6B6B6B",
  manhattan_blue: "#404456",
  white_smoke: "#F5F5F6",
  bg_grey: "#f8f8f8",
  dark_charcoal: "#333",
  bastille: "#323234",
};
export const APIS = {
  // Cheack: "https://api-mobile.contact.eg/auth/password/checkExistence",
  // SendOTP: "https://api-mobile.contact.eg/auth/sendOtp",
  // VerifyOTP: "https://api-mobile.contact.eg/auth/verifyOtp",
  // UpdatePass: "https://api-mobile.contact.eg/auth/updatePassword",
  // Login: "https://api-mobile.contact.eg/auth/login",
  // baseURL: "https://api-mobile.contact.eg",
  baseURL: "https://api-mobile-staging.contact.eg/amr-api/v1",
};
export const EnvKey = {
  secretKey: process.env.NEXT_PUBLIC_SECRET_KEY_Token,
};
//
